export const PERMISSIONS = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  CUSTOMER_VIEW: 'CUSTOMER_VIEW',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_GENERATE: 'REPORT_GENERATE',
  REPORT_DOWNLOAD: 'REPORT_DOWNLOAD',
  SETTINGS_VIEW: 'SETTINGS_VIEW',
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  RBAC_MANAGE: 'RBAC_MANAGE',
  APPROVAL_VIEW: 'APPROVAL_VIEW',
  APPROVAL_CREATE: 'APPROVAL_CREATE',
  APPROVAL_APPROVE: 'APPROVAL_APPROVE',
  APPROVAL_REJECT: 'APPROVAL_REJECT',
  USER_FIELD: 'USER_FIELD',
  AUDIT_VIEW: 'AUDIT_VIEW',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
